# Generated by Django 6.0 on 2025-12-29 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('concept', 'Concept'), ('bug', 'Bug'), ('learning', 'Learning'), ('mistake', 'Mistake'), ('project_issue', 'Project Issue'), ('interview_insight', 'Interview Insight'), ('optimization', 'Optimization'), ('cheatsheet', 'Cheatsheet'), ('algorithm', 'Algorithm')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('react', 'React'), ('unity', 'Unity'), ('sql', 'SQL'), ('html_css', 'HTML/CSS'), ('github', 'GitHub')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_topic', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database'), ('game_dev', 'Game Development')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_topic', models.CharField(max_length=100)),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugbook.maintopic')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_subtopic', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('main_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugbook.maintopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('note_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugbook.notetype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugbook.programminglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='GenericDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_explanation', models.CharField(max_length=500)),
                ('note_reasoning', models.CharField(blank=True, max_length=500, null=True)),
                ('note_misconception', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bugbook.note')),
            ],
        ),
        migrations.AddField(
            model_name='maintopic',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='topics', to='bugbook.programminglanguage'),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='bugbook.note')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugbook.programminglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='bugbook.maintopic')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugbook.subtopic'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='bugbook.tag'),
        ),
        migrations.AddField(
            model_name='maintopic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugbook.topiccategory'),
        ),
    ]
