# Generated by Django 6.0 on 2026-01-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbook', '0002_user_alter_note_user_alter_tag_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericdetails',
            name='title',
            field=models.CharField(help_text='Provide title for the note', max_length=100, null=True),
        ),
    ]
